### PR TITLE
Delete user fix

### LINKED ISSUE #45: Delete users listings when deleting a user
When a user is deleted all their listings must be deleted as well. At the moment deleting a user with existing listings results in foreign key constraint.

### PR DESCRIPTION
**Pull request by JesseWeHaveToCook**
Fixes #45 Delete user now deletes listings that he owns and removes all assignments on listings that he was assigned to.

### CODE REVIEW

**Comment by pckv** [comment]
Can you change the ListingRepository functions to `findByOwner` and `findByAssignee` instead? This way you can use the User object provided in `deleteUser`

**Comment by JesseWeHaveToCook** [comment]
Ok, I've changed it.

**Comment by EspenK** [comment]
Thank you! You can edit the pull request text to include `fixes #45` so that merging this will automatically close the issue.

**Review by pckv — APPROVED** [review]
Thanks!

**Comment by EspenK** [comment]
I meant to put `fixes #45` in the description of the pull request. Sorry for not being clear on where to put it.

**Review by EspenK — APPROVED** [review]

**Pull request merged**
